### ISSUE TITLE
Listen for event when window is out of focus

### ISSUE THREAD

**Issue by friendlymatthew** [friendlymatthew/leptos-hotkeys#1]
Steps to recreate:

1. Press cmd+g
2. close find in page
3. tap ctrl

from @blackjackhack
*I have a feeling it's because it registers the key press of g, but doesn't unregister it when the window loses focus. Then, when it regains focus, it still thinks g is pressed, and a ctrl completes the ctrl+g combo*

**Comment by rakshith-ravi** [comment]
*blackjackhack. Not hawk haha. Anyways, that's me. Just commenting here to stay subscribed to the issue

**Comment by gihrig** [comment]
Seems this issue might conflict with #2 "Support Sticky Keys" as that feature wants modified key behavior to persist after the window looses focus.

**Comment by friendlymatthew** [comment]
> Seems this issue might conflict with #2 "Support Sticky Keys" as that feature wants modified key behavior to persist after the window looses focus.

@rakshith-ravi's issue relates to when the window loses focus which should reset the global state of pressed keys. 

#2's feature request is introducing a cooldown threshold where after a key is pressed, we listen to additional key presses within the threshold. 

I think both #1 and #2 can be solved 🤠

**Comment by gihrig** [comment]
@friendlymatthew As you describe it, I agree there is no conflict.

The potential for conflict I see is in my use case where the key binding remains active after the app window looses focus or is closed, so the window could be re-focused by that delayed key stroke.

It seems to me this is what #1 was having a problem with?

**Comment by friendlymatthew** [comment]
> The potential for conflict I see is in my use case where the key binding remains active after the app window looses focus or is closed, so the window could be re-focused by that delayed key stroke.

Oh I see. Yes this fix and #2 might not mix well, if the desired effect is to continue listen to key strokes when it's within a cooldown period but the window loses focus.


To address this, we can have additional options, to opt out of resetting the `keys_pressed` state when the window loses focus. By default we'll have the behavior #1 wants to solve

**Comment by gihrig** [comment]
> By default we'll have the behavior https://github.com/friendlymatthew/leptos-hotkeys/issues/1 wants to solve

Sounds like the right choice.

**Comment by rakshith-ravi** [comment]
@gihrig does a window losing focus still mean we continue to keep the binding active? Usually a window losing focus would mean we clear the key_pressed bindings. The accessibility issue would be the case if the same window is in focus and we allow for gaps in between keys. But even in that case, the window wouldn't lose focus, would it?

**Comment by gihrig** [comment]
@rakshith-ravi 
> does a window losing focus still mean we continue to keep the binding active?

The use case is for something like an instantly available note taking app. What used to be called "terminate and stay resident".

The idea being that the window is hidden and the app is "sleeping" so other apps can have focus, then the note taking app can be instantly focused at the press of a key.

It would be nice for this to be managed internally by the note taking app, but one could argue that this hot key should be an OS key mapping feature.

**Comment by rakshith-ravi** [comment]
Given this is for leptos, if the window loses focus, any further keystrokes will not be detected. And even if it was, I'm not sure there's a way to bring it to foreground. I do agree that it should be an OS key binding rather than a website key binding
