### ISSUE TITLE
Remove the need to use `.to_string()` in `HotkeysContext`

### ISSUE THREAD

**Issue by friendlymatthew** [friendlymatthew/leptos-hotkeys#24]
https://github.com/friendlymatthew/leptos-hotkeys/blob/adce93f0afc333e80c211975e72b79167dd7897b/example/demo/src/app.rs#L56-L65

When we toggle_scope, we have to cast into `.to_string()`. Let's change this to a macro? Also let's double check that `enable_scope` and `disable_scope` also has this feature

**Comment by JustBobinAround** [comment]
This actually isn't possible with the current way `HotkeysProvider` works. Since `toggle_scope` is a Callback, there is no accessible function at compile time. 
```rust
    let HotkeysContext { toggle_scope, .. } = use_hotkeys_context();
    // toggle_scope is only accessible after construction and var name is not known yet
```

Lifetimes aren't really easily applicable hear either.
